blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://community.serversideup.net/t/read-me-getting-help-with-financial-freedom/461/
    about: Get friendly support from the community on our forum.

  - name: âœ¨ Request a feature
    url: https://community.serversideup.net/t/requesting-features-for-financial-freedom/460/
    about: Learn how to request a new feature.

  - name: ğŸ¤µ Get Professional Support & Customizations
    url: https://serversideup.net/get-help/?quick_question=financialfreedom
    about: Skip the line and get priority support directly from the creators of Financial Freedom.