blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://github.com/serversideup/financial-freedom/discussions
    about: Get friendly support from the community on our forum.

  - name: âœ¨ Request a feature
    url: https://github.com/serversideup/financial-freedom/discussions/63
    about: Learn how to request a new feature.

  - name: ğŸ¤µ Get Professional Support & Customizations
    url: https://serversideup.net/professional-support
    about: Skip the line and get priority support directly from the creators of Financial Freedom.